; GATE ARRAY

; REGISTRES GATE ARRAY
GA_PORT_H        EQU #7F		; Les valeurs 78 a 7f sont valides pour outi par ex
GA_PORT          EQU #7F00
GA_SELECT_COL    EQU #00
GA_SELECT_COLOR  EQU #00
GA_SELECT_BORDER EQU #10 
GA_SET_COL       EQU #40
GA_SET_COLOR     EQU #40
GA_SET_MODE      EQU #8C

MACRO GA_SET_INK INK,COL
		LD      BC,GA_PORT | GA_SELECT_COL | {INK}
        OUT     (C),C 
		LD      A,GA_SET_COL | {COL}  
        OUT     (C),A
MEND

MACRO GA_SET_BORDER COL
		LD      BC,GA_PORT | GA_SELECT_BORDER
        OUT     (C),C 
		LD      A,GA_SET_COL | {COL}  
        OUT     (C),A
MEND

; Il faut definir un flag DEBUG pour utiliser cette macro
MACRO DEBUG_BORDER col
	if DEBUG==1
	GA_SET_BORDER {col}
	else	
	GA_SET_BORDER COL_BLACK
	endif
MEND

COL_BLACK 			EQU #14
COL_BLUE 			EQU #04
COL_BLUE_BRIGHT		EQU #15
COL_RED 			EQU #1C
COL_MAGENTA 		EQU #18
COL_MAUVE			EQU #1D
COL_RED_BRIGHT		EQU #0C
COL_PURPLE			EQU #05
COL_MAGENTA_BRIGHT 	EQU #0D
COL_GREEN			EQU #16
COL_CYAN			EQU #06
COL_BLUE_SKY 		EQU #17
COL_YELLOW 			EQU #0E
COL_GREY			EQU #00
COL_BLUE_PASTEL		EQU #1F
COL_ORANGE 			EQU #0E
COL_PINK			EQU #07
COL_MAGENTA_PASTEL  EQU #0F
COL_GREEN_BRIGHT	EQU #12
COL_GREEN_SEA		EQU #02
COL_CYAN_BRIGHT		EQU #13
COL_GREEN_LIME 		EQU #1A
COL_GREEN_PASTEL	EQU #19
COL_CYAN_PASTEL		EQU #1B
COL_YELLOW_BRIGHT	EQU #0A
COL_YELLOW_PASTEL	EQU #03
COL_WHITE  			EQU #0B


GA_BLUE 			EQU GA_SET_COL | #04
GA_BLACK 			EQU GA_SET_COL | #14
GA_BLUE_BRIGHT		EQU (GA_SET_COL | #15)
GA_RED 				EQU (GA_SET_COL | #1C)
GA_MAGENTA 			EQU GA_SET_COL | #18
GA_MAUVE			EQU GA_SET_COL | #1D
GA_RED_BRIGHT		EQU GA_SET_COL | #0C
GA_PURPLE			EQU GA_SET_COL | #05
GA_MAGENTA_BRIGHT 	EQU GA_SET_COL | #0D
GA_GREEN			EQU GA_SET_COL | #16
GA_CYAN				EQU GA_SET_COL | #06
GA_BLUE_SKY 		EQU GA_SET_COL | #17
GA_YELLOW 			EQU GA_SET_COL | #0E
GA_GREY				EQU GA_SET_COL | #00
GA_BLUE_PASTEL		EQU GA_SET_COL | #1F
GA_ORANGE 			EQU GA_SET_COL | #0E
GA_PINK				EQU GA_SET_COL | #07
GA_MAGENTA_PASTEL  	EQU GA_SET_COL | #0F
GA_GREEN_BRIGHT		EQU GA_SET_COL | #12
GA_GREEN_SEA		EQU GA_SET_COL | #02
GA_CYAN_BRIGHT		EQU GA_SET_COL | #13
GA_GREEN_LIME 		EQU GA_SET_COL | #1A
GA_GREEN_PASTEL		EQU GA_SET_COL | #19
GA_CYAN_PASTEL		EQU GA_SET_COL | #1B
GA_YELLOW_BRIGHT	EQU GA_SET_COL | #0A
GA_YELLOW_PASTEL	EQU GA_SET_COL | #03
GA_WHITE  			EQU GA_SET_COL | #0B




MACRO COLGRAD9 c1,c2
defb GA_SET_COL|{c1},GA_SET_COL|{c1},GA_SET_COL|{c1},GA_SET_COL|{c2},GA_SET_COL|{c1},GA_SET_COL|{c1},GA_SET_COL|{c2},GA_SET_COL|{c2},GA_SET_COL|{c1}
MEND

; palette.asm?	
MACRO PALETTE_GRAD
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_RED
	COLGRAD9 COL_RED, 	COL_RED_BRIGHT
	COLGRAD9 COL_RED_BRIGHT, COL_ORANGE
	COLGRAD9 COL_ORANGE,  COL_YELLOW
	COLGRAD9 COL_YELLOW,  COL_WHITE
	COLGRAD9 COL_WHITE,	23
	COLGRAD9 23, 21
	COLGRAD9 21, 4
	COLGRAD9 21, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK
	COLGRAD9 COL_BLACK, COL_BLACK

	
	
	COLGRAD9 COL_BLACK, 4
	COLGRAD9 4, 21
	COLGRAD9 21, 23
	COLGRAD9 23,11
	COLGRAD9 11,18
	COLGRAD9 18, 22 
	COLGRAD9 22, 20
	COLGRAD9 20, 20
	
	COLGRAD9 20, 20
	COLGRAD9 20, 22
	COLGRAD9 22 , 2
	COLGRAD9 22 , 2
MEND
